# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Adam Worley
tagline:             'Computer Scientist'
description:         'Please use this navigation to find my pages, I hope to include more detailed posts and other information here in the future.'
url:                 http://mada360.me
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Adam Worley
  url:               https://twitter.com/mdo
  email:             worley9@gmail.com

# Custom vars
version:             1.0.0
